version: 2
updates:
- package-ecosystem: nuget
  directory: "/DScannerX/DScannerX"
  schedule:
    interval: weekly
    time: "10:00"
  ignore:
    - dependency-name: "Xamarin.UITest"
    - dependency-name: "Microsoft.NET.Test.Sdk"
    - dependency-name: "NUnit3TestAdapter"
  open-pull-requests-limit: 10
  labels:
  - kind/dependency
  - do-not-merge/work-in-progress
